complete -c starman -n "__fish_use_subcommand" -l no-color -d 'Disable ANSI colors (also respects NO_COLOR)'
complete -c starman -n "__fish_use_subcommand" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c starman -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c starman -n "__fish_use_subcommand" -f -a "tui" -d 'Interactive full-screen TUI (requires a TTY on stdout)'
complete -c starman -n "__fish_use_subcommand" -f -a "version" -d 'Print version and exit'
complete -c starman -n "__fish_use_subcommand" -f -a "completion" -d 'Print shell completion script to stdout (redirect or eval — see long help)'
complete -c starman -n "__fish_use_subcommand" -f -a "doctor" -d 'Check paths, config, and basic environment'
complete -c starman -n "__fish_use_subcommand" -f -a "create-user" -d 'Create a UNIX user with shell snippets, optional group & Linuxbrew (requires root)'
complete -c starman -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c starman -n "__fish_seen_subcommand_from tui" -l no-color -d 'Disable ANSI colors (also respects NO_COLOR)'
complete -c starman -n "__fish_seen_subcommand_from tui" -s h -l help -d 'Print help'
complete -c starman -n "__fish_seen_subcommand_from tui" -s V -l version -d 'Print version'
complete -c starman -n "__fish_seen_subcommand_from version" -l no-color -d 'Disable ANSI colors (also respects NO_COLOR)'
complete -c starman -n "__fish_seen_subcommand_from version" -s h -l help -d 'Print help'
complete -c starman -n "__fish_seen_subcommand_from version" -s V -l version -d 'Print version'
complete -c starman -n "__fish_seen_subcommand_from completion" -l no-color -d 'Disable ANSI colors (also respects NO_COLOR)'
complete -c starman -n "__fish_seen_subcommand_from completion" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c starman -n "__fish_seen_subcommand_from completion" -s V -l version -d 'Print version'
complete -c starman -n "__fish_seen_subcommand_from doctor" -l no-color -d 'Disable ANSI colors (also respects NO_COLOR)'
complete -c starman -n "__fish_seen_subcommand_from doctor" -s h -l help -d 'Print help'
complete -c starman -n "__fish_seen_subcommand_from doctor" -s V -l version -d 'Print version'
complete -c starman -n "__fish_seen_subcommand_from create-user" -s g -l group -d '协作 UNIX 组（默认见配置 `default_user_group`，一般为 lab）' -r
complete -c starman -n "__fish_seen_subcommand_from create-user" -l shell -d '登录 shell（默认见配置 `default_shell`）' -r
complete -c starman -n "__fish_seen_subcommand_from create-user" -l home-quota -d '家目录所在文件系统上的用户磁盘配额（软/硬相同，块配额）；如 `200G`、`500M`。默认 200G，见配置 `default_home_quota`' -r
complete -c starman -n "__fish_seen_subcommand_from create-user" -l no-brew -d '不初始化 Linuxbrew（跳过 `brew bundle`）'
complete -c starman -n "__fish_seen_subcommand_from create-user" -l no-quota -d '不设置磁盘配额（忽略默认 200G）'
complete -c starman -n "__fish_seen_subcommand_from create-user" -l no-color -d 'Disable ANSI colors (also respects NO_COLOR)'
complete -c starman -n "__fish_seen_subcommand_from create-user" -s h -l help -d 'Print help'
complete -c starman -n "__fish_seen_subcommand_from create-user" -s V -l version -d 'Print version'
complete -c starman -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tui; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from doctor; and not __fish_seen_subcommand_from create-user; and not __fish_seen_subcommand_from help" -f -a "tui" -d 'Interactive full-screen TUI (requires a TTY on stdout)'
complete -c starman -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tui; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from doctor; and not __fish_seen_subcommand_from create-user; and not __fish_seen_subcommand_from help" -f -a "version" -d 'Print version and exit'
complete -c starman -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tui; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from doctor; and not __fish_seen_subcommand_from create-user; and not __fish_seen_subcommand_from help" -f -a "completion" -d 'Print shell completion script to stdout (redirect or eval — see long help)'
complete -c starman -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tui; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from doctor; and not __fish_seen_subcommand_from create-user; and not __fish_seen_subcommand_from help" -f -a "doctor" -d 'Check paths, config, and basic environment'
complete -c starman -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tui; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from doctor; and not __fish_seen_subcommand_from create-user; and not __fish_seen_subcommand_from help" -f -a "create-user" -d 'Create a UNIX user with shell snippets, optional group & Linuxbrew (requires root)'
complete -c starman -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tui; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from doctor; and not __fish_seen_subcommand_from create-user; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
